name: Gerar Video IPTV

on:
  schedule:
    - cron: '0 * * * *' # Roda a cada 1 hora
  workflow_dispatch: # Permite rodar manualmente clicando num botão

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Rodar Script
        env: 
          MEUS_LINKS: ${{ secrets.MEUS_LINKS }}
        run: python gerar.py

      - name: Salvar Video no Repositório
        run: |
          git config --global user.name 'Bot IPTV'
          git config --global user.email 'bot@noreply.github.com'
          git add video_status.mp4
          git commit -m "Atualizando status video" || echo "Nada mudou"
          git push
